### ISSUE TITLE
Design Web Application Deployment Script : For Jenkins in Future

### ISSUE THREAD

**Issue by marri005** [marri005/login-page#3]
1. Create a shell script with following specification within devops branch
2. Update the System
3 Install Following List Of Utilities in Server: zip,unzip
4. Install HTTP server  NgINX WEb sERVER!
D-Remove Sample test pages from Web Server i.e /var/www/html
B. Login App Repository - https://github.com/marri005/login-page.git
K. Create Login App to Nginx Server Document Root i. e /var/www/html
8. Verify Server is Loading Login App

**Comment by marri0043** [comment]
WEBDELOPYMENT APP IS DONE
